language: node_js

node_js:
  - "10"

before_script:
  - npm run build

before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis

deploy:
  - provider: npm
    api_key:
      secure: "rXUQhEuaPgU9aAbje3FgprFzTpCJbZajYAgHlVXj+Q08Z6QYrblesV5fx4aGvVndxTMHbABF+iIHKGOV/5HoppQAzx5GY3bjsJ2e0Osnf7dt1A/g/uUnSyVv7lp4Fzo6xjOre7JJkQNsxKev/wKMcg09duGoKZ/wZFyYUC6JP1Lu+nO6Yiad9QVu6X5hJisFv82Cay3TWw9jK2KKiHACLMS31TcjJT3E1NxY9ahSxiiYFkt9IsUVp00ZPA2KxWe21T50uulsm49tVNgutL11TuoAVncd/9BKZ5c0ZPEk+T7nvRL5i4gLl1ZaH3q1Zq0Ek21J5BRx9vV+mIf9KAv9REFnlsCApQOmxzUvPbtxjuerORHG4WN+SwmolhAuU0M9fgwV6IhTNjorQKsORf1x28/D+WqCdIcpXIeO5XqPUl9QP67VcYLfemT1UGO+wMGlKio4vpbou6+9kXxEuqU3Bl9p4N7oPTyV4mTYMvi/Da7lB+pFFW5t4JSDbzJ+51WjYL3C3D06wJjpvapekm8AIqXJ1OjIaUwFcL8f3apypcvb6/1agpx7x1Q0xSZswMXwRR/Wgi1Dg9ot55/p4ac8g4ePSN3WqlIULsROJijv8WLxEpK3oIl/WsZZvmnFHb0FGTkoS8c2gmK0EEyQ97OYp9eFOEA7bA+gABzQB8vpTzU="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "rXUQhEuaPgU9aAbje3FgprFzTpCJbZajYAgHlVXj+Q08Z6QYrblesV5fx4aGvVndxTMHbABF+iIHKGOV/5HoppQAzx5GY3bjsJ2e0Osnf7dt1A/g/uUnSyVv7lp4Fzo6xjOre7JJkQNsxKev/wKMcg09duGoKZ/wZFyYUC6JP1Lu+nO6Yiad9QVu6X5hJisFv82Cay3TWw9jK2KKiHACLMS31TcjJT3E1NxY9ahSxiiYFkt9IsUVp00ZPA2KxWe21T50uulsm49tVNgutL11TuoAVncd/9BKZ5c0ZPEk+T7nvRL5i4gLl1ZaH3q1Zq0Ek21J5BRx9vV+mIf9KAv9REFnlsCApQOmxzUvPbtxjuerORHG4WN+SwmolhAuU0M9fgwV6IhTNjorQKsORf1x28/D+WqCdIcpXIeO5XqPUl9QP67VcYLfemT1UGO+wMGlKio4vpbou6+9kXxEuqU3Bl9p4N7oPTyV4mTYMvi/Da7lB+pFFW5t4JSDbzJ+51WjYL3C3D06wJjpvapekm8AIqXJ1OjIaUwFcL8f3apypcvb6/1agpx7x1Q0xSZswMXwRR/Wgi1Dg9ot55/p4ac8g4ePSN3WqlIULsROJijv8WLxEpK3oIl/WsZZvmnFHb0FGTkoS8c2gmK0EEyQ97OYp9eFOEA7bA+gABzQB8vpTzU="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "mqskyoXkL+FdJSsCygL4Qh78OVcxm90y6U54g1AK3rlD3hA7uFRPVroY/Vt2hqeZpmCxF0KFZlfloq4dWS22myx49jP3bm94CtZKrb/7ePVcUcDJn8nMLJLTT6rDJnUWMJmY0rce//NafBma6PRXXuyQ/dnTcOgTGUxF/7nLU7pGpIlE/5HC66zCsGWKbiQD6Doh8Gzm8oZdU5WcB4QjbwykvtEVtcOZXCtqGi9YcVafQ0dWmiMRsVa6cAnBz5+w/0O6p5bHx/8sxKgREUcVPOKyAy/Ck7Ijoc+KmbpEhirFQQSebkziiC2YwrE2gUX5RqqseQptYM6vqVD7VR8ZBUwQa/3I3IcuIgTP/9fUPrYYwKYtkQtmUhn5w/mxfr3kWCWp2KSGkT8Hhwgas5wa99/qJIFoGbv5qWvnmS79KyxZo7fJctlmnBVMkGolwYjRWGKtg944Lt0Ydw8N1IVowvRkNasohgEzYaZqz3vAjxoIF/SyAfqxVMrpXYuepBsSwD4U65i9hliLKyiRogK9W59HQefHxVA+YobX11OzS/8pIrO30KndyWLWWO/avuxih/JIswViYHfMwqf/H4iCgyIUj2BH85ZDjjYNhNJ/fD6GskNo3oQRYITOsQj6SocsG8K61dtmSNLQDKUUY9d1ItqqcU8rBiQ5U4Dv85HyME8="
    on:
      tags: true
    skip_cleanup: true
