name: Publish release

on:
  release:
    types: [created]

jobs:
  call-workflow:
    permissions:
      contents: write
      pages: write
      id-token: write
    secrets: inherit
    uses: compulim/workflows/.github/workflows/publish-release.yml@main
    with:
      package-name: on-error-resume-next
      tag: ${{ github.ref_name }}
